TV5-VolunteerEventMgmtApp/Models/Director.cs
using System.ComponentModel.DataAnnotations;

namespace TV5_VolunteerEventMgmtApp.Models
{
    public class Director : IValidatableObject
    {
        public int ID { get; set; }

        [Display(Name = "First Name")]
        [Required(ErrorMessage = "A first name is required when adding a new choir director.")]
        [StringLength(64, ErrorMessage = "A first name must be less than 64 characters long.")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "A Last Name is required when creating a director.")]
        [StringLength(128, ErrorMessage ="A last name must be less than 128 characters long.")]
        public string LastName { get; set; }

        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "A Phone number is required when creating a director.")]
        [Phone(ErrorMessage = "Please enter a valid phone number")]
        [DataType(DataType.PhoneNumber, ErrorMessage = "Please enter a valid phone number")]
        [StringLength(10, ErrorMessage = "A phone number must be 10 numbers long.", MinimumLength = 10)]
        public string PhoneNumber { get; set; }

        [Display( Name = "Email Address")]
        [EmailAddress(ErrorMessage = "Please enter a valid EmailAddress")]
        [Required(ErrorMessage = "An email address is requiured when creating a director.")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Please enter a valid EmailAddress")]
        [StringLength(128, ErrorMessage = "An email must be less than 128 characters long.")]
        public string Email { get; set; }

        public bool IsActive { get; set; } = true;

        public string FullName { get { return NameSummary(); } }

        
        public ICollection<DirectorLocation> DirectorLocations { get; set; } = new HashSet<DirectorLocation>();

        public ICollection<AttendanceSheet> AttendanceSheets { get; set; } = new HashSet<AttendanceSheet>();


        public string NameSummary()
        {
            return $"{FirstName} {LastName}";
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if(DirectorLocations.Count()  == 0)
            {
                yield return new ValidationResult("A director requires at least one location", ["DirectorLocations"]);
            }
        }
    }
}

TV5-VolunteerEventMgmtApp/Models/Location.cs
using System.ComponentModel.DataAnnotations;
namespace TV5_VolunteerEventMgmtApp.Models
{
    public class Location
    {
        public int ID { get; set; }

        [Display(Name = "City")]
        [Required(ErrorMessage ="You cannot create a location without a city.")]
        [MaxLength(125, ErrorMessage = "City name cannot exeed 125 characters.")]
        public string City { get; set; }

        
        public string Color { get; set; }


        public bool IsActive { get; set; } = true;



        public ICollection<DirectorLocation> DirectorLocations { get; set; } = new HashSet<DirectorLocation>();

        public ICollection<VolunteerEvent> VolunteerEvents { get; set; } = new HashSet<VolunteerEvent>();   

        public ICollection<AttendanceSheet> AttendanceSheets { get; set; } = new HashSet<AttendanceSheet>();

        public ICollection<Venue> Venues { get; set; } = new HashSet<Venue>();

        public ICollection<SingerLocation> SingerLocations { get; set; } = new HashSet<SingerLocation>();

        public ICollection<VolunteerLocation> VolunteerLocations { get; set;} = new HashSet<VolunteerLocation>();

    }
}

TV5-VolunteerEventMgmtApp/Models/Singer.cs
using System.ComponentModel.DataAnnotations;

namespace TV5_VolunteerEventMgmtApp.Models
{
    public class Singer : IValidatableObject
    {

        public int Id { get; set; }

		[Display(Name = "Phone")]
		public string PhoneFormatted => "(" + Phone?.Substring(0, 3) + ") "
			+ Phone?.Substring(3, 3) + "-" + Phone?[6..];

		[Display(Name ="First Name")]
        [StringLength(128, ErrorMessage = "A first name must be less than 128 characters long.")]
        [Required(ErrorMessage = "Please enter a first name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Please enter a last name")]
        [StringLength(128, ErrorMessage = "A last name must be less than 128 characters long.")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "Date of Birth")]
        [Required(ErrorMessage ="Please enter the singers DOB")]
        public DateOnly DOB { get; set; }

        [Display(Name = "Emergency Contact")]
        [StringLength(128, ErrorMessage = "Contact name must be less than 128 characters long.")]
        public string? EmergencyContactName { get; set; }

        [Display(Name = "Relation to Singer")]
        public ContactRelation? Relation { get; set; }

        [Display(Name ="Notes")]
        [MaxLength(500, ErrorMessage = "personal notes cannot exceed 500 characters.")]
        public string? Notes { get; set; }


        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage ="Please enter a valid email address.")]
        public string? Email { get; set; }
        [Display(Name = "Phone Number")]
        [Phone(ErrorMessage = "Please enter a valid phone number.")]
        [StringLength(10, ErrorMessage = "A phone number must be 10 numbers long.", MinimumLength = 10)]
        [DataType(DataType.PhoneNumber)]
        public string? Phone {  get; set; }

        public bool isActive { get; set; } = true;

        public ICollection<Attendee> Attendance {  get; set; } = new HashSet<Attendee>();

		[Display(Name = "Locations")]
		public ICollection<SingerLocation> SingerLocation { get; set; } = new HashSet<SingerLocation>();

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (DOB > DateOnly.FromDateTime(DateTime.Now.AddYears(-8))){
                yield return new ValidationResult("Singers must be at least 8 years old.");
            }
            if (DOB < DateOnly.FromDateTime(DateTime.Now.AddYears(-18)))
            {
                yield return new ValidationResult("Singers cannot be over the age of 18.");
            }      
        }
    }
}

TV5-VolunteerEventMgmtApp/Controllers/CsvImportController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TV5_VolunteerEventMgmtApp.Data;
using TV5_VolunteerEventMgmtApp.Models;
using TV5_VolunteerEventMgmtApp.Services;
using TV5_VolunteerEventMgmtApp.Utilities;
using TV5_VolunteerEventMgmtApp.Utilities.Csv;
using TV5_VolunteerEventMgmtApp.ViewModels;

namespace TV5_VolunteerEventMgmtApp.Controllers
{
    [Route("[controller]")]
    public class CsvImportController : Controller
    {
        private List<string> DefaultColors = new List<string> { "#4CAF50", "#2196F3", "#9C27B0", "#00BCD4", "#8BC34A", "#607D8B" };
        private readonly CsvService _csvService;
        private readonly VolunteerEventMgmtAppDbContext _context;
        public CsvImportController(CsvService csvService, VolunteerEventMgmtAppDbContext ctx)
        {
            _csvService = csvService;
            _context = ctx;
        }

        [HttpGet, Route("Singer")]
        public IActionResult Singer()
        {

            ViewBag.Locations = LocationSelectList();
            return View();
        }

        [HttpPost, Route("Singer")]

        public async Task<IActionResult> Singer(int locationId, IFormFile csvFile)
        { // if json is returned at least some of the records were created 
            // bad request means something went wrong (most likely invalid CSV)
            ViewBag.Locations = LocationSelectList();
            var location = await _context.Locations.FirstOrDefaultAsync(c => c.ID == locationId);
            if (location == null)
            {
                ModelState.AddModelError("", "There is no location with the ID " + locationId);
                return View(new CsvUploadVM<List<SingerCsvUpload>>
                {
                    Data = new List<SingerCsvUpload>()
                });
            }

            ViewBag.Locations = LocationSelectList(selected: locationId);
            if (csvFile != null && csvFile.Length > 0)
            {
                try
                {
                    var newSingers = ReadSingerCsv(csvFile);

                    //var csvErrors = ValidateAndAddSingers(newSingers, location, out var dbErrors, out var successCount);
                    var csvErrors = ValidateSingers(newSingers);

                    if (!csvErrors.All(s => s.IsValid))
                    {
                        MapModelStateErrors(csvErrors);
                        return View(new CsvUploadVM<List<SingerCsvUpload>>
                        {
                            Data = new List<SingerCsvUpload>()
                        });
                        
                        //return Json(new
                        //{
                        //    csvErrors
                        //});
                    }

                    var dbErrors = await AddSingersToDb(newSingers, location);

                    MapModelStateErrors(csvErrors);
                    MapModelStateErrors(dbErrors.Errors);
					//return Json(new
					//{
					//    csvErrors,
					//    dbErrors
					//});
					TempData["SuccessMessage"] = $"Singers added.";
					return View(new CsvUploadVM<List<SingerCsvUpload>>
                    {
                        Data = newSingers,
                        SuccessCount = dbErrors.SuccessCount
                    });
                }
                catch (ApplicationException ex)
                { // invalid csv errors
                    Console.WriteLine(ex.Message);
					TempData["FailMessage"] = $"Unable to import singers.";
					ModelState.AddModelError("", ex.Message);
                }
                catch (Exception ex)
                {
					TempData["FailMessage"] = $"Unable to import singers.";
					//return BadRequest(StaticMessages.UnknownError);
					ModelState.AddModelError("", ex.Message);
                }

            }
            else
            {
				//return BadRequest(StaticMessages.InvalidCSV);
				TempData["FailMessage"] = $"Unable to import singers.";
				ModelState.AddModelError("", "Please select a valid CSV file.");
            }
            return View(new CsvUploadVM<List<SingerCsvUpload>>
            {
                Data = new List<SingerCsvUpload>()
            });
        }

        [HttpGet, Route("Director")]
        public IActionResult Director()
        {
            return View();
        }


        [HttpPost, Route("Director")]
        public async Task<IActionResult> Director(IFormFile csvFile)
        {

            if (csvFile != null && csvFile.Length > 0)
            {
                //List<DirectorCsvUpload> newLocations = null;
                try
                {
                    var newDirectors = ReadDirectorCsv(csvFile);
                    Console.WriteLine(newDirectors);
                    var csvErrors = ValidateDirectors(newDirectors);
                    if (!csvErrors.All(s => s.IsValid))
                    {

                        //return Json(new
                        //{
                        //    csvErrors,
                        //});
                        MapModelStateErrors(csvErrors);
                        return View(new CsvUploadVM<List<DirectorCsvUpload>>
                        {
                            Data = new List<DirectorCsvUpload>()
                        });
                    }

                    var dbErrors = await AddDirectorsToDb(newDirectors);

                    MapModelStateErrors(csvErrors);
                    MapModelStateErrors(dbErrors.Errors);

					//return Json(new
					//{
					//    csvErrors,
					//    dbErrors
					//});
					TempData["SuccessMessage"] = $"Directors added.";
					return View(new CsvUploadVM<List<DirectorCsvUpload>>
                    {
                        Data = newDirectors,
                        SuccessCount = dbErrors.SuccessCount
                    });
                }
                catch (ApplicationException ex)
                { // invalid csv errors
                    Console.WriteLine(ex.Message);
					TempData["FailMessage"] = $"Unable to import directors.";
					ModelState.AddModelError("",ex.Message);
                    //return BadRequest(StaticMessages.UnknownError);
                }
                catch (Exception ex)
                {
					TempData["FailMessage"] = $"Unable to import directors.";
					ModelState.AddModelError("", StaticMessages.UnknownError);
                }


            }
            else
            {
				TempData["FailMessage"] = $"Unable to import directors.";
				ModelState.AddModelError("", StaticMessages.InvalidCSV);
            }
            return View(new CsvUploadVM<List<DirectorCsvUpload>>
            {
                Data = new List<DirectorCsvUpload>()
            });

        }


        [HttpGet, Route("Location")]
        public IActionResult Location()
        {
            return View();
        }

        [HttpPost, Route("Location")]
        public async Task<IActionResult> Location(IFormFile csvFile)
        {

            if (csvFile != null && csvFile.Length > 0)
            {
                try
                {
                    var newLocations = ReadLocationCsv(csvFile);

                    var csvErrors = ValidateLocations(newLocations);
                    if (!csvErrors.All(s => s.IsValid))
                    {
                        MapModelStateErrors(csvErrors);
                        return View(new CsvUploadVM<List<LocationCsvUpload>>
                        {
                            Data = new List<LocationCsvUpload>()
                        });
                        //return Json(new
                        //{
                        //    csvErrors
                        //});
                    }

                    var dbErrors = await AddLocationsToDb(newLocations);
                    MapModelStateErrors(csvErrors);
                    MapModelStateErrors(dbErrors.Errors);

					//return Json(new
					//{
					//    dbErrors,
					//
					//    csvErrors,
					//});
					TempData["SuccessMessage"] = $"Locations Added.";
					return View(new CsvUploadVM<List<LocationCsvUpload>>
                    {
                        Data = newLocations,
                        SuccessCount = dbErrors.SuccessCount
                    });
                }
                catch (ApplicationException ex)
                { // invalid csv errors
                    Console.WriteLine(ex.Message);
					TempData["FailMessage"] = $"Unable to import locations.";
					ModelState.AddModelError("", ex.Message);
                    //return Json(new
                    //{
                    //    ex.Message,
                    //});
                }
            }
            else
            {
				//return Json(new
				//{
				//    Message = "Please submit a valid CSV file"
				//});
				TempData["FailMessage"] = $"Unable to import locations.";
				ModelState.AddModelError("", "Please select a valid CSV file.");
            }
             return View(new CsvUploadVM<List<LocationCsvUpload>>
            {
                Data = new List<LocationCsvUpload>()
            });
        }

        private List<CsvValidationResponse> ValidateLocations(List<LocationCsvUpload> locations)
        {
            int lineCount = 1;
            var errors = new List<CsvValidationResponse>();
            //var failedToAdd = new List<string>();
            foreach (var location in locations)
            {
                var valid = location.IsValid();
                if (!valid.IsValid)
                {
                    valid.LineOfRecord = lineCount;
                    errors.Add(valid);

                }

                lineCount++;

            }


            return errors;
        }

        private async Task<DbErrorCollection> AddLocationsToDb(List<LocationCsvUpload> locations)
        {
            var collection = new DbErrorCollection();
            //int success = 0;

TV5-VolunteerEventMgmtApp/Views/CsvImport/Director.cshtml
@model TV5_VolunteerEventMgmtApp.ViewModels.CsvUploadVM<List<DirectorCsvUpload>>



    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="container">
    <h1 class="text-purple">Upload Director Data</h1>
    <div>
        <h2 class="text-purple">Example Header</h2>
        <span class="fw-bold pb-3 d-block">FirstName,LastName,Email,PhoneNumber,LocationName</span>
    </div>
        <form asp-controller="CsvImport" asp-action="Director" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <input type="file" name="csvFile" class="form-control" required>
            </div>
            <button type="submit" class="btn btn-purple">Upload</button>
        </form>
        @if (Model != null && Model.Data.Any())
        {
            <h2>Data Preview (@Model.SuccessCount successfully created)</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone Number</th>
                        <th>Location Name</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var user in Model.Data)
                    {
                        <tr>
                            <td>@user.FirstName</td>
                            <td>@user.LastName</td>
                            <td>@user.Email</td>
                            <td>@user.PhoneNumber</td>
                            <td>@user.LocationName</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>

TV5-VolunteerEventMgmtApp/Views/CsvImport/Index.cshtml
@model IEnumerable<TV5_VolunteerEventMgmtApp.Models.SingerCsvUpload>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CSV File Upload</title>
    <link rel="stylesheet" href="~/css/site.css">
</head>
<body>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="container">
        <h1>Upload Singer Data</h1>
        <form asp-controller="CsvImport" asp-action="Index" method="post" enctype="multipart/form-data" >
            <select asp-items="@ViewBag.Locations" name="locationId">
                <option>Select a Location</option>
            </select>
            <div class="form-group">
                <input type="file" name="csvFile" class="form-control" required>
            </div>
            <button type="submit" class="btn btn-primary">Upload</button>
        </form>
        @if (Model != null && Model.Any())
        {
            <h2>Singers Uploaded</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone Number</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var user in Model)
                    {
                        <tr>
                            <td>@user.FirstName</td>
                            <td>@user.LastName</td>
                            <td>@user.Email</td>
                            <td>@user.PhoneNumber</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</body>
</html>

TV5-VolunteerEventMgmtApp/Views/CsvImport/Location.cshtml
@model TV5_VolunteerEventMgmtApp.ViewModels.CsvUploadVM<List<LocationCsvUpload>>

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="container">
    <h1 class="text-purple">Upload Location Data</h1>
    <div>
        <h2 class="text-purple">Example Header</h2>
        <span class="fw-bold pb-3 d-block">City,DirectorFirstName,DirectorLastName,DirectorPhone,DirectorEmail</span>
    </div>
        <form asp-controller="CsvImport" asp-action="Location" method="post" enctype="multipart/form-data">
           
            <div class="form-group">
                <input type="file" name="csvFile" class="form-control" required>
            </div>
            <button type="submit" class="btn btn-purple">Upload</button>
        </form>
        @if (Model != null && Model.Data.Any())
        {
            <h2>Data Preview (@Model.SuccessCount successfully created)</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Chapter</th>
                        <th>Director First</th>
                        <th>Director Last</th>
                        <th>Director Email</th>
                        <th>Director Phone</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var user in Model.Data)
                    {
                        <tr>
                            <td>@user.City</td>
                            <td>@user.DirectorFirstName</td>
                            <td>@user.DirectorLastName</td>
                            <td>@user.DirectorEmail</td>
                            <td>@user.DirectorPhone</td>

                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>

TV5-VolunteerEventMgmtApp/Views/CsvImport/Singer.cshtml
@model TV5_VolunteerEventMgmtApp.ViewModels.CsvUploadVM<List<SingerCsvUpload>>

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="container">
        <h1 class="text-purple">Upload Singer Data</h1>
    <div>
        <h2 class="text-purple">Example Header</h2>
        <span class="fw-bold pb-3 d-block">FirstName,LastName,Email,PhoneNumber,ContactName</span>
    </div>
        <form asp-controller="CsvImport" asp-action="Singer" method="post" enctype="multipart/form-data" >
            <select class="form-control mb-2" asp-items="@ViewBag.Locations" name="locationId">
                <option>Select a Location</option>
            </select>
            <div class="form-group">
                <input type="file" name="csvFile" class="form-control" required>
            </div>
            <button type="submit" class="btn btn-purple">Upload</button>
        </form>
        
        @if (Model != null && Model.Data.Any())
        {
            <h2>Data Preview (@Model.SuccessCount successfully created)</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Contact Email</th>
                        <th>Contact Phone</th>
                        <th>Contact Name</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var user in Model.Data)
                    {
                        <tr>
                            <td>@user.FirstName</td>
                            <td>@user.LastName</td>
                            <td>@user.Email</td>
                            <td>@user.PhoneNumber</td>
                            <td>@user.ContactName</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>